# Generated by Harry DS Alsyundawy on Sat Mar 22 05:14:53 PM WIB 2025,Binary Defense Systems Artillery Threat Intelligence Feed and Banlist Feed
/ip firewall address-list
rem [find list=00_BinaryDefense]
