# Generated by Harry DS Alsyundawy on Fri Mar 21 01:14:48 AM WIB 2025,Binary Defense Systems Artillery Threat Intelligence Feed and Banlist Feed
/ip firewall address-list
rem [find list=00_BinaryDefense]
