# Generated by Harry DS Alsyundawy on 2026-02-01T03:33:04Z, source: https://lists.blocklist.de/lists/ftp.txt
/ip firewall address-list
rem [find list="00_blocklist_ftp"]
add list="00_blocklist_ftp" address=8.215.69.55 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=14.33.253.65 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=36.238.212.194 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=103.181.26.210 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=106.58.222.91 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=115.86.253.254 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=121.206.62.167 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=123.110.169.47 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=156.245.205.68 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=167.148.195.117 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=169.150.197.8 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=175.123.249.121 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=194.90.71.246 comment="Blocklist.de FTP"
