# Generated by Harry DS Alsyundawy on 2025-12-18T23:33:04Z, source: https://lists.blocklist.de/lists/ftp.txt
/ip firewall address-list
rem [find list="00_blocklist_ftp"]
add list="00_blocklist_ftp" address=14.17.126.136 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=47.242.70.231 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=101.231.133.210 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=113.88.166.218 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=113.106.4.98 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=125.124.0.46 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=156.245.205.68 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=185.92.139.43 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=202.111.131.240 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=211.9.57.22 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=211.9.57.29 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=213.230.71.159 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=222.231.57.34 comment="Blocklist.de FTP"
