# Generated by Harry DS Alsyundawy on 2025-12-17T23:33:05Z, source: https://lists.blocklist.de/lists/ftp.txt
/ip firewall address-list
rem [find list="00_blocklist_ftp"]
add list="00_blocklist_ftp" address=14.17.126.136 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=103.174.52.162 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=113.234.190.155 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=120.55.99.107 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=121.148.71.200 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=121.177.27.248 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=125.34.171.202 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=190.171.108.25 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=202.111.131.240 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=211.9.57.22 comment="Blocklist.de FTP"
add list="00_blocklist_ftp" address=211.9.57.29 comment="Blocklist.de FTP"
