# Generated by Harry DS Alsyundawy on 2026-08-11T09:46:01Z, source: https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/ips/doh.txt
/ip firewall address-list
rem [find list="00_DOH-DOT"]
