# Generated by Harry DS Alsyundawy on Thu May  8 04:27:16 PM WIB 2025, the blocked IP is reported block dshield
/ip firewall address-list
rem [find list=00_dshield]
add list=00_dshield address=45.148.10.0/24 comment=dshield
add list=00_dshield address=57.129.64.0/24 comment=dshield
add list=00_dshield address=65.49.1.0/24 comment=dshield
add list=00_dshield address=83.222.191.0/24 comment=dshield
add list=00_dshield address=89.248.165.0/24 comment=dshield
add list=00_dshield address=91.196.152.0/24 comment=dshield
add list=00_dshield address=104.234.115.0/24 comment=dshield
add list=00_dshield address=104.255.152.0/24 comment=dshield
add list=00_dshield address=108.181.24.0/24 comment=dshield
add list=00_dshield address=147.185.132.0/24 comment=dshield
add list=00_dshield address=154.81.156.0/24 comment=dshield
add list=00_dshield address=167.94.138.0/24 comment=dshield
add list=00_dshield address=185.91.127.0/24 comment=dshield
add list=00_dshield address=185.218.84.0/24 comment=dshield
add list=00_dshield address=193.163.125.0/24 comment=dshield
add list=00_dshield address=198.235.24.0/24 comment=dshield
add list=00_dshield address=205.210.31.0/24 comment=dshield
add list=00_dshield address=206.168.34.0/24 comment=dshield
add list=00_dshield address=208.87.242.0/23 comment=dshield
