# Generated by Harry DS Alsyundawy on Fri May 23 06:31:56 AM WIB 2025, the blocked IP is reported block dshield
/ip firewall address-list
rem [find list="00_dshield"]
add list=00_dshield address=45.156.128.0/23 comment=dshield
add list=00_dshield address=64.62.156.0/24 comment=dshield
add list=00_dshield address=83.222.191.0/24 comment=dshield
add list=00_dshield address=91.196.152.0/24 comment=dshield
add list=00_dshield address=147.185.132.0/24 comment=dshield
add list=00_dshield address=154.212.141.0/24 comment=dshield
add list=00_dshield address=167.94.138.0/24 comment=dshield
add list=00_dshield address=167.94.145.0/24 comment=dshield
add list=00_dshield address=167.94.146.0/24 comment=dshield
add list=00_dshield address=176.65.148.0/24 comment=dshield
add list=00_dshield address=185.218.84.0/24 comment=dshield
add list=00_dshield address=185.218.86.0/24 comment=dshield
add list=00_dshield address=185.242.226.0/24 comment=dshield
add list=00_dshield address=193.163.125.0/24 comment=dshield
add list=00_dshield address=195.82.146.0/24 comment=dshield
add list=00_dshield address=195.184.76.0/24 comment=dshield
add list=00_dshield address=199.45.154.0/24 comment=dshield
add list=00_dshield address=205.210.31.0/24 comment=dshield
add list=00_dshield address=206.168.34.0/24 comment=dshield
