# Generated by Harry DS Alsyundawy on Sat Jan  8 01:00:01 EST 2022, the blocked IP is reported block dshield
/ip firewall address-list
add list=00_dshield address=5.188.206.0/24 comment=dshield
add list=00_dshield address=45.134.26.0/24 comment=dshield
add list=00_dshield address=45.135.232.0/24 comment=dshield
add list=00_dshield address=45.137.23.0/24 comment=dshield
add list=00_dshield address=45.143.203.0/24 comment=dshield
add list=00_dshield address=45.146.164.0/24 comment=dshield
add list=00_dshield address=45.146.166.0/24 comment=dshield
add list=00_dshield address=45.155.205.0/24 comment=dshield
add list=00_dshield address=89.248.163.0/24 comment=dshield
add list=00_dshield address=89.248.165.0/24 comment=dshield
add list=00_dshield address=92.63.196.0/23 comment=dshield
add list=00_dshield address=138.99.216.0/24 comment=dshield
add list=00_dshield address=138.199.32.0/24 comment=dshield
add list=00_dshield address=146.88.240.0/24 comment=dshield
add list=00_dshield address=167.248.133.0/24 comment=dshield
add list=00_dshield address=183.136.226.0/24 comment=dshield
add list=00_dshield address=185.191.34.0/24 comment=dshield
add list=00_dshield address=193.27.229.0/24 comment=dshield
add list=00_dshield address=193.163.125.0/24 comment=dshield
