# Generated by Harry DS Alsyundawy on 2026-02-04T21:33:04Z, source: https://feodotracker.abuse.ch/downloads/ipblocklist.txt
/ip firewall address-list
rem [find list="00_feodo"]
add list="00_feodo" address=34.204.119.63 comment="Feodo Tracker"
add list="00_feodo" address=167.86.75.145 comment="Feodo Tracker"
add list="00_feodo" address=172.232.59.14 comment="Feodo Tracker"
