# Generated by Harry DS Alsyundawy on 2025-10-28T23:33:02Z, source: https://feodotracker.abuse.ch/downloads/ipblocklist.txt
/ip firewall address-list
rem [find list="00_feodo"]
add list="00_feodo" address=137.184.9.29 comment="Feodo Tracker"
