# Generated by Harry DS Alsyundawy on 2026-01-17T07:33:04Z, source: https://feodotracker.abuse.ch/downloads/ipblocklist.txt
/ip firewall address-list
rem [find list="00_feodo"]
add list="00_feodo" address=34.204.119.63 comment="Feodo Tracker"
add list="00_feodo" address=50.16.16.211 comment="Feodo Tracker"
add list="00_feodo" address=137.184.9.29 comment="Feodo Tracker"
add list="00_feodo" address=162.243.103.246 comment="Feodo Tracker"
add list="00_feodo" address=167.86.75.145 comment="Feodo Tracker"
