# Generated by Harry DS Alsyundawy on 2026-05-11T21:33:12Z, source: https://herrbischoff.com/code/me/country-ip-blocks/raw/branch/master/ipv4/id.cidr
/ip firewall address-list
rem [find list="00_indonesia_ip_addr"]
