# Generated by Harry DS Alsyundawy on 2026-04-18T22:48:16Z, source: https://herrbischoff.com/code/me/country-ip-blocks/raw/branch/master/ipv6/id.cidr (IPv6)
/ipv6 firewall address-list
rem [find list="00_indonesia_ipv6_addr"]
