# Generated by Harry DS Alsyundawy on 2026-03-10T03:53:08Z, source: https://raw.githubusercontent.com/herrbischoff/country-ip-blocks/master/ipv6/id.cidr (IPv6)
/ipv6 firewall address-list
rem [find list="00_indonesia_ipv6_addr"]
