# Generated by Harry DS Alsyundawy on 16-09-2024 20:00:04, the blocked IP is reported block malc0de
/ip firewall address-list
rem [find list=00_malc0de]
add list=00_malc0de address=50.63.202.57 comment=malc0de
add list=00_malc0de address=62.173.145.104 comment=malc0de
add list=00_malc0de address=69.167.178.28 comment=malc0de
add list=00_malc0de address=79.96.191.147 comment=malc0de
add list=00_malc0de address=79.98.28.30 comment=malc0de
add list=00_malc0de address=85.93.145.251 comment=malc0de
add list=00_malc0de address=91.189.114.7 comment=malc0de
add list=00_malc0de address=94.23.64.40 comment=malc0de
add list=00_malc0de address=103.83.81.144 comment=malc0de
add list=00_malc0de address=103.129.98.17 comment=malc0de
add list=00_malc0de address=103.253.73.77 comment=malc0de
add list=00_malc0de address=104.18.36.98 comment=malc0de
add list=00_malc0de address=107.175.64.210 comment=malc0de
add list=00_malc0de address=108.171.216.194 comment=malc0de
add list=00_malc0de address=110.4.45.119 comment=malc0de
add list=00_malc0de address=184.168.221.43 comment=malc0de
add list=00_malc0de address=185.104.45.20 comment=malc0de
add list=00_malc0de address=185.174.100.116 comment=malc0de
add list=00_malc0de address=185.193.38.74 comment=malc0de
add list=00_malc0de address=192.138.20.112 comment=malc0de
add list=00_malc0de address=217.174.152.68 comment=malc0de
