#!/bin/sh
saveTo=/var/www/html/www/mikrotik-blacklist/
now=$(date);
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level1.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level1.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level1.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level1 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level1.rsc

echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level2.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level2.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level2.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level2 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level2.rsc

echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level3.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level3.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level3.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level3 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level3.rsc

echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level4.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level4.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level4.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level4 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level4.rsc

echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_webserver.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_webserver.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_webserver.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_webserver address=" $1 " comment=firehol_webserver";}' >> $saveTo/firehol_webserver.rsc

echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_webclient.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_malware.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_webclient.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_malware address=" $1 " comment=firehol_malware";}' >> $saveTo/firehol_malware.rsc


echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_abusers_1d.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_abusers_1d.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_abusers_1d.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_abusers_1d address=" $1 " comment=firehol_abusers_1d";}' >> $saveTo/firehol_abusers_1d.rsc

echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_abusers_30d.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_abusers_30d.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_abusers_30d.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_abusers_30d address=" $1 " comment=firehol_abusers_30d";}' >> $saveTo/firehol_abusers_30d.rsc

echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/bruteforceblocker.rsc
echo "/ip firewall address-list" >> $saveTo/bruteforceblocker.rsc
wget -q -O - http://danger.rulez.sk/projects/bruteforceblocker/blist.php | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_bruteforceblocker address=" $1 " comment=bruteforceblocker";}' >> $saveTo/bruteforceblocker.rsc

wget https://www.axarva.co.id/blacklist-ip/dshield.rsc -O /var/www/html/www/mikrotik-blacklist/dshield.rsc
wget https://www.axarva.co.id/blacklist-ip/blocklist.rsc -O /var/www/html/www/mikrotik-blacklist/blocklist.rsc
wget https://www.axarva.co.id/blacklist-ip/spamhaus.rsc -O /var/www/html/www/mikrotik-blacklist/spamhaus.rsc