#!/bin/sh
#
# Mikrotik RBL Address List Maker
# 
# CopyLeft (C) 2021 Harry DS Alsyundawy <alsyundawy@gmail.com>
#
# Distributed under terms of the MIT license.
#


saveTo=/var/www/html/www/mikrotik-blacklist/
now=$(date);
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level1.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level1.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level1.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level1 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level1.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level2.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level2.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level2.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level2 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level2.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level3.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level3.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level3.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level3 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level3.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_level4.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_level4.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_level4.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_level4 address=" $1 " comment=firehol_level1";}' >> $saveTo/firehol_level4.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_webserver.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_webserver.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_webserver.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_webserver address=" $1 " comment=firehol_webserver";}' >> $saveTo/firehol_webserver.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_malware.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_malware.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_webclient.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_malware address=" $1 " comment=firehol_malware";}' >> $saveTo/firehol_malware.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_abusers_1d.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_abusers_1d.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_abusers_1d.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_abusers_1d address=" $1 " comment=firehol_abusers_1d";}' >> $saveTo/firehol_abusers_1d.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_abusers_30d.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_abusers_30d.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_abusers_30d.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_abusers_30d address=" $1 " comment=firehol_abusers_30d";}' >> $saveTo/firehol_abusers_30d.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_proxies.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_proxies.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_proxies.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_proxies address=" $1 " comment=firehol_proxies";}' >> $saveTo/firehol_proxies.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now" > $saveTo/firehol_anonymous.rsc
echo "/ip firewall address-list" >> $saveTo/firehol_anonymous.rsc
wget -q -O - https://iplists.firehol.org/files/firehol_anonymous.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_firehol_anonymous address=" $1 " comment=firehol_anonymous";}' >> $saveTo/firehol_anonymous.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now, the blocked IP is reported block SSH bruteforce attacks from danger.rulez.sk" > $saveTo/bruteforceblocker.rsc
echo "/ip firewall address-list" >> $saveTo/bruteforceblocker.rsc
wget -q -O - https://iplists.firehol.org/files/bruteforceblocker.ipset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_bruteforceblocker address=" $1 " comment=bruteforceblocker";}' >> $saveTo/bruteforceblocker.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now, the blocked IP is reported block spam from spamhaus" > $saveTo/spamhaus.rsc
echo "/ip firewall address-list" >> $saveTo/spamhaus.rsc
wget -q -O - https://iplists.firehol.org/files/spamhaus_drop.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_spamhaus address=" $1 " comment=Spamhaus";}' >> $saveTo/spamhaus.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now, the blocked IP is reported block Evolution of voipbl From VoIPBL.org" > $saveTo/voip-bl.rsc
echo "/ip firewall address-list" >> $saveTo/voip-bl.rsc
wget -q -O - https://iplists.firehol.org/files/voipbl.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_voip-blacklist address=" $1 " comment=VOIP-RBL";}' >> $saveTo/voip-bl.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now, the blocked IP is reported block BLOCKLIST.DE" > $saveTo/blocklist.rsc
echo "/ip firewall address-list" >> $saveTo/blocklist.rsc
wget -q -O - https://iplists.firehol.org/files/blocklist_de.ipset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_blocklist address=" $1 " comment=BLOCKLIST.DE";}' >> $saveTo/blocklist.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now, the blocked IP is reported block malc0de" > $saveTo/malc0de.rsc
echo "/ip firewall address-list" >> $saveTo/malc0de.rsc
wget -q -O - https://iplists.firehol.org/files/malc0de.ipset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_malc0de address=" $1 " comment=malc0de";}' >> $saveTo/malc0de.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now, the blocked IP is reported block dshield" > $saveTo/dshield.rsc
echo "/ip firewall address-list" >> $saveTo/dshield.rsc
wget -q -O - https://iplists.firehol.org/files/dshield.netset | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_dshield address=" $1 " comment=dshield";}' >> $saveTo/dshield.rsc
######################################################################################################################################################################
echo "# Generated by Harry DS Alsyundawy on $now, DNS Public List" > $saveTo/dns-public.rsc
echo "/ip firewall address-list" >> $saveTo/dns-public.rsc
wget -q -O - https://public-dns.info/nameservers-all.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=00_dns-public address=" $1 " comment=dns-public";}' >> $saveTo/dns-public.rsc
######################################################################################################################################################################

rm -rf /var/www/html/www/mikrotik-blacklist/nice.rsc
wget -cq http://ixp.mikrotik.co.id/download/nice.rsc -O /var/www/html/www/mikrotik-blacklist/nice.rsc
######################################################################################################################################################################
rm -rf /var/www/html/www/app/cache/*
######################################################################################################################################################################
