# Generated by Harry DS Alsyundawy on 2026-04-14T09:33:06Z, source: https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/ips/tif.txt
/ip firewall address-list
rem [find list="00_TIF"]
