# Generated by Harry DS Alsyundawy on 2026-08-13T09:25:12Z, source: https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/ips/tif.txt
/ip firewall address-list
rem [find list="00_TIF"]
