# Generated by Harry DS Alsyundawy on Thu Feb 13 12:27:18 AM WIB 2025, the blocked IP is reported negative content from TRUSTPOSITIF KOMINFO
/ip firewall address-list
rem [find list=00_TrustPositifList]
